# Generated by Django 5.2.3 on 2025-10-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='ficha',
            field=models.FileField(blank=True, null=True, upload_to='modulos/'),
        ),
    ]
