# Generated by Django 5.2.3 on 2025-06-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(null=True)),
                ('nro_curso', models.IntegerField()),
                ('cupo_maximo', models.PositiveIntegerField(default=50)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=8, null=True)),
                ('url_info', models.URLField(max_length=150, null=True)),
                ('modalidad', models.CharField(choices=[('virtual', 'Virtual'), ('presencial', 'Presencial'), ('hibrida', 'Híbrida')], default='virtual', max_length=20, null=True)),
            ],
        ),
    ]
