# Generated by Django 5.2.3 on 2025-11-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_modulo_ficha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='fecha_inscripcion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
