# Generated by Django 5.2.3 on 2025-11-12 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_inscripcion_fecha_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('presente', models.BooleanField(default=False)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.inscripcion')),
            ],
        ),
    ]
