# Generated by Django 5.2.3 on 2025-06-19 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_inscripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstudiantePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(max_length=20)),
                ('biografia', models.TextField(null=True)),
                ('recibe_novedades', models.BooleanField(default=True)),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.estudiante')),
            ],
        ),
    ]
